### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by Chike1990**
I cloned an article page of the New York Times applying the concepts I learned over the week. Specifically,
I first created a repository on Github, created a branch from it, added ReadMe file,  added linter checks, index.html file, and style.css file.
The structure and content of the New York Times article page were laid out in HTML- using HTML 5 semantic tags; the images were downloaded from the NYT page and were included in the cloned web page; these contents were style using CSS - and by applying concepts like positioning, flex, float, etc.
In other words, this page includes a navbar, an aside, main, sections, articles, divs, footer, etc. Prior to sending a pull request, linters were checked for errors in the style and index files and about five code reviewers reviewed this code and made recommendations that have been included.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
# Status::Invalid❗️

# Hi team,

#### Make sure the linter check on this repository are all passing and submit a new code review request😇.

#### Thank You

Happy coding

**Comment by Chike1990** [comment]
I cloned an article page of the New York Times applying the concepts I learned over the week. Specifically,
I first created a repository on Github, created a branch from it, added ReadMe file, added linter checks, index.html file, and style.css file.
The structure and content of the New York Times article page were laid out in HTML- using HTML 5 semantic tags; the images were downloaded from the NYT page and were included in the cloned web page; these contents were style using CSS - and by applying concepts like positioning, flex, float, etc.
In other words, this page includes a navbar, an aside, main, sections, articles, divs, footer, etc. Prior to sending a pull request, linters were checked for errors in the style and index files and about five code reviewers reviewed this code and made recommendations that have been included.

**Review by Georjane — CHANGES_REQUESTED** [review]
## Status: Changes Required 🛑 🔧 
### Hi there Team ✋🏽 
Wow, this is incredibly amazing! Your project looks perfect and just like the original design. 💯 
We just have some finishing touches to do to get this project approved:

- [ ] Please kindly remove all inline comments in your code
- [ ] The embedded video in the screenshot below is slightly not aligned to the center with the rest of the text.
centerimg

- [ ] Please add a live link to your Readme file too

### Nice to have:

- [ ] It would be nice to have a more descriptive branch name
- [ ] Also to improve on your project directory structure, you could create an image or assets folder and place all your images in there.

_Feel free to reach out to me on Slack if you have any questions, Witah Georjane_ 🤝 
Good luck on your project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

**Comment by Chike1990** [comment]
Thanks

**Pull request closed without merging**
